package com.tanla.template_matching.Utils;

import java.util.List;

public class Messages {
        public static List<String> message_template_names = List.of("alert_1", "app_1", "apps_and_features_01",
                        "commodity_0630",
                        "vw45", "welcome_message", "enquiry_update_rcnt", "informaes_avalista", "hack4_provi",
                        "template_4",
                        "teacher_slots_new", "vw45", "teacher_slots_new", "trial_certificate_unlock",
                        "trial_com_24hours_new_apt",
                        "hack4_provi", "commodity_0630");
        public static List<String> messages = List.of(
                        "As requested by you, here is a stock recommendation.\n\nBuy ABC Corporation\nTarget price $120\nBuy now using this link: www.example.com\n\nWarm Regards,\nTeam MOFSL",
                        "Dear John Doe,\n\nHope you have successfully logged in to the App or through the Website. If yes, we would like to guide you on some MUST KNOW features in our *Mobile Apps* which will help you with your *long-term investing and daily trading*. \nAll you need to do is select the App which suits your needs and start your investments TODAY.\n\nClick here to know about *key features* on our app: www.example.com/features\n\nIf you haven't started yet, download our *MO Investor App:* www.example.com/investor or *MO Trader App:* www.example.com/trader\n\nWarm Regards,\nTeam MOFSL",
                        "Dear Alice Johnson,\n\nHope you have successfully logged in to the App or through the Website. If yes, we would like to guide you on some MUST KNOW features in our Mobile Apps which will help you with your long-term investing and daily trading. \nAll you need to do is select the App which suits your needs and start your investments TODAY.\n\nClick here to know about key features on our app: www.example.com/features\n\nIf you haven't started yet, download our MO Investor App: https://appurl.io/j95arm2a or MO Trader App: https://appurl.io/jcioj1bc\n\nWarm Regards,\nTeam MOFSL",
                        "Dear Jane Smith,\n\nAs requested by you, Motilal Oswal brings to you MO Research - Commodity Option's Idea.\n\nWe recommend to buy Gold, sell Silver at $25.50, Target Price: $27.00, Stop Loss: $24.00, Generated on: September 3, 2024\n\nPlace your trade through MO Investor App: https://appurl.io/investor or MO Trader App: https://appurl.io/trader now!\n\nWarm Regards,\nTeam MOFSL",
                        "Hi Team Alpha,\nYour profile is incomplete. Upload albums onto your WMG Profile to start getting leads: www.example.com/upload",
                        "Dear Sarah Lee,\nThank you for registering for the event with Jobsforher. We are extremely excited to see you at the event on October 15, 2024!\nYou can reply with “STOP” anytime you wish to stop communication through this channel.",
                        "Dear Alex Johnson,\n\nThank you for your interest in Tata Intra. We have received your enquiry and will get back to you shortly.\n\nIn the meantime, if you wish to get more information, please:\n\n▪ Reply *1* to receive a brochure of the Tata Intra vehicle\n▪ Reply *2* to schedule a test drive\n▪ Reply *3* to raise another enquiry\n\nAt any time, to receive the latest information and updates regarding Tata Intra, message ℹ *\"info\"* to this number.\n\nIf you wish to stop receiving communication from Tata Intra, please reply *“STOP”* to unsubscribe.\n\nTata Intra Team",
                        "Olá Maria Silva, tudo bem?\nGostaríamos de informar que sua fatura já está disponível para pagamento.\nSua fatura está com a data de vencimento no dia 15 de setembro de 2024, e você consegue acessá-la pelo link enviado ao seu email.\n\nEssa é uma mensagem automática, e qualquer dúvida estamos à disposição.",
                        "Oi Lucas Oliveira, tudo ótimo?\n\nVocê mandou muito bem no ProviHack4Good e olha só... a empresa Tech Innovations está querendo bater um papo com você. No link abaixo você terá acesso à agenda da pessoa recrutadora dessa empresa. Escolha o melhor horário para você. Se prepare e boa sorte!\n\nEntre neste link e arrase: www.example.com/agenda",
                        "Dear Parent,\n\nHello from WhiteHat Jr!\n\nWell-spaced classes are essential for your child's effective learning. We see a delay of over 2 weeks in your child's classes. Kindly call us on +1-800-123-4567 or click this WhatsApp link: https://wa.me/18001234567 to continue seamless learning. You can also login and book classes from your dashboard: https://code.whitehatjr.com/s/login\n\nRegards,\nTeam Whitehat Jr",
                        "Dear Alex Carter,\n\nOur algorithm has identified perfect slots for you to increase your trial conversion chances by 93%.\n\nOpen Surge Slots now!\nhttps://www.example.com/surge-slots\n\nClick here to go to your scheduler: https://www.example.com/scheduler\n\nThanks,\nWhiteHat Jr Team",
                        "Hi Team Bravo,\nYour profile is incomplete. Upload albums onto your WMG Profile to start getting leads: www.example.com/upload",
                        "Dear Jamie Lee,\n\nOur algorithm has identified perfect slots for you to increase your trial conversion chances by 93%.\n\nOpen Surge Slots now!\nhttps://www.example.com/surge-slots\n\nClick here to go to your scheduler: https://www.example.com/scheduler\n\nThanks,\nWhiteHat Jr Team",
                        "Dear Emma Johnson,\n\nCongrats! John Smith is now a Certified Coding Fundamentals Expert!\n\nView the certificate and share this proud moment with friends and family! https://www.example.com/certificate\n\nThank you,\nWhiteHat Jr Education Team",
                        "Dear Olivia Brown,\n\nYou are among the top 20% of students to take this class.\n\nWe have only 1 spot left in our coding course with your trial teacher! Please review the full curriculum link here\n\nhttps://www.example.com/curriculum\n\nOur academic counselors would like to use your feedback to improve the curriculum. You can call us on +1-800-555-1234.\n\nThanks,\nWhiteHat Jr Education Team",
                        "Oi João Pereira, tudo ótimo?\n\nVocê mandou muito bem no ProviHack4Good e olha só... a empresa Tech Solutions está querendo bater um papo com você. No link abaixo você terá acesso à agenda da pessoa recrutadora dessa empresa. Escolha o melhor horário para você. Se prepare e boa sorte!\n\nEntre neste link e arrase: https://www.example.com/agenda",
                        "Dear Alex Carter,\n\nAs requested by you, Motilal Oswal brings to you MO Research - Commodity Option's Idea.\n\nWe recommend to Alex Carter, Buy Gold Futures at $1,800, Target Price: $1,850, Stop Loss: $1,780, Generated on : September 30, 2024\n\nPlace your trade through MO Investor App https://www.example.com/investor-app or MO Trader App https://www.example.com/trader-app now!\n\nWarm Regards,\nTeam MOFSL");

        public static List<String> exampleTexts = List.of(
                        "As requested by you here is a stock recommendation.\n\nBuy ABC Corp\nTarget price 1500\nBuy now using this link www.stocklink.com\n\nWarm Regards,\nTeam MOFSL",
                        "As requested by you here is a stock recommendation.\n\nBuy XYZ Ltd\nTarget price 1200\nBuy now using this link www.tradelink.com\n\nWarm Regards,\nTeam MOFSL",

                        "Dear John,\n\nAs requested by you, Motilal Oswal brings to you MO Research - Commodity Option's Idea.\n\nWe recommend to Buy, Gold Futures at 1800, Target Price: 2000, Stop Loss: 1700, Generated on : 01-Sep-2024\n\nPlace your trade through MO Investor App www.app1.com or MO Trader App www.app2.com now!\n\nWarm Regards,\nTeam MOFSL",
                        "Dear Jane,\n\nAs requested by you, Motilal Oswal brings to you MO Research - Commodity Option's Idea.\n\nWe recommend to Sell, Silver Options at 25, Target Price: 28, Stop Loss: 24, Generated on : 02-Sep-2024\n\nPlace your trade through MO Investor App www.app1.com or MO Trader App www.app2.com now!\n\nWarm Regards,\nTeam MOFSL",

                        "Dear Customer,\n\nBasis your past transactions, you can opt for this research call Buy ABC Shares\n\nThank you.",
                        "Dear Customer,\n\nBasis your past transactions, you can opt for this research call Invest in Mutual Funds\n\nThank you.",

                        "Hey,\n\nWe are delighted to inform you about the Annual Employee Drive:\n\nDrive Name : *Team Building*\nDuration: *2 Days*\nQualification Criteria: *All Employees*\nReward: *Gift Vouchers*\n\n*Terms and Conditions:*\nParticipation is mandatory.\nRewards are non-transferable.\nEvent schedule is subject to change.\nAny misconduct will lead to disqualification.\n\n*SUCCESS HAS NO LIMITATIONS, EXCEPT THE ONES YOU MAKE*",
                        "Hey,\n\nWe are delighted to inform you about the Charity Fundraiser Drive:\n\nDrive Name : *Charity Run*\nDuration: *1 Week*\nQualification Criteria: *Volunteers Only*\nReward: *Certificate of Participation*\n\n*Terms and Conditions:*\nAll proceeds go to charity.\nParticipants must register in advance.\nEvent may be rescheduled due to weather.\nSponsors are welcome.\n\n*SUCCESS HAS NO LIMITATIONS, EXCEPT THE ONES YOU MAKE*",

                        "Hi Team Marketing,\nYour profile is incomplete. Upload albums onto your WMG Profile to start getting leads: www.link.com",
                        "Hi Team Sales,\nYour profile is incomplete. Upload albums onto your WMG Profile to start getting leads: www.profilelink.com",

                        "Dear Alex,\n\nOur algorithm has identified perfect slots for you to increase your trial conversion chances by 93%.\n\nOpen Surge Slots now!\nwww.link.com\n\nClick here to go to your scheduler: www.schedulerlink.com\n\nThanks,\nWhiteHat Jr Team",
                        "Dear Sarah,\n\nOur algorithm has identified perfect slots for you to increase your trial conversion chances by 93%.\n\nOpen Surge Slots now!\nwww.slotslink.com\n\nClick here to go to your scheduler: www.scheduler.com\n\nThanks,\nWhiteHat Jr Team",

                        "Dear Mark,\n\nCongrats! John is now a Certified Coding Fundamentals Expert!\n\nView the certificate and share this proud moment with friends and family! www.certificate.com\n\nThank you,\nWhiteHat Jr Education Team",
                        "Dear Emily,\n\nCongrats! Emma is now a Certified Coding Fundamentals Expert!\n\nView the certificate and share this proud moment with friends and family! www.sharecertificate.com\n\nThank you,\nWhiteHat Jr Education Team",

                        "Dear David,\n\nYou are among the top 20% of students to take this class.\n\nWe have only 1 spot left in our coding course with your trial teacher! Please review the full curriculum link here\n\nwww.curriculumlink.com\n\nOur academic counsellors would like to use your feedback to improve the curriculum. You can call us on 123-456-7890.\n\nThanks,\nWhiteHat Jr Education Team",
                        "Dear Sophia,\n\nYou are among the top 20% of students to take this class.\n\nWe have only 1 spot left in our coding course with your trial teacher! Please review the full curriculum link here\n\nwww.fullcurriculum.com\n\nOur academic counsellors would like to use your feedback to improve the curriculum. You can call us on 098-765-4321.\n\nThanks,\nWhiteHat Jr Education Team",

                        "Oi João, tudo ótimo? \n\nVocê mandou muito bem no ProviHack4Good e olha só... a empresa Tech Corp está querendo bater um papo com você. No link abaixo você terá acesso à agenda da pessoa recrutadora dessa empresa. Escolha o melhor horário para você. Se prepare e boa sorte!\n\nEntre neste link e arrase: www.recruiterlink.com",
                        "Oi Maria, tudo ótimo? \n\nVocê mandou muito bem no ProviHack4Good e olha só... a empresa Innovatech está querendo bater um papo com você. No link abaixo você terá acesso à agenda da pessoa recrutadora dessa empresa. Escolha o melhor horário para você. Se prepare e boa sorte!\n\nEntre neste link e arrase: www.schedulelink.com",

                        "Dear John,\n\nThank You for interest in Tata Intra, we have received your enquiry and we will get back to you shortly.\n\nIn the meanwhile, if you wish to get more information then please\n\n▪Reply *1* to receive a brochure of the Tata Intra vehicle\n▪Reply *2* to schedule a test drive\n▪Reply *3* to raise another enquiry\n\nAt anytime, to receive latest information and updates regarding Tata Intra, message ℹ *\"info\"* to this number.\n\nIf you wish to stop receiving communication from Tata Intra, please reply  *\"STOP\"* to unsubscribe.\n\nTata Intra Team",
                        "Dear Emma,\n\nThank You for interest in Tata Intra, we have received your enquiry and we will get back to you shortly.\n\nIn the meanwhile, if you wish to get more information then please\n\n▪Reply *1* to receive a brochure of the Tata Intra vehicle\n▪Reply *2* to schedule a test drive\n▪Reply *3* to raise another enquiry\n\nAt anytime, to receive latest information and updates regarding Tata Intra, message ℹ *\"info\"* to this number.\n\nIf you wish to stop receiving communication from Tata Intra, please reply  *\"STOP\"* to unsubscribe.\n\nTata Intra Team",

                        "Dear Investor,\n\nHope you have successfully logged in the App or through Website. If yes, we would like to guide you on some MUST KNOW features in our *Mobile Apps* which will help you with your *long-term investing and daily trading*. \nAll you need to do is select the App which suits your needs and start your investments  TODAY.\n\nClick here to know about *key features* on our app: www.featurelink.com\n\nIf you haven't started yet, download our *MO Investor App:*  www.moinvestorapp.com or *MO Trader App:*  www.motraderapp.com\n\nWarm Regards,\nTeam MOFSL",
                        "Dear Trader,\n\nHope you have successfully logged in the App or through Website. If yes, we would like to guide you on some MUST KNOW features in our *Mobile Apps* which will help you with your *long-term investing and daily trading*. \nAll you need to do is select the App which suits your needs and start your investments  TODAY.\n\nClick here to know about *key features* on our app: www.knowfeatures.com\n\nIf you haven't started yet, download our *MO Investor App:*  www.appinvestor.com or *MO Trader App:*  www.apptrader.com\n\nWarm Regards,\nTeam MOFSL",

                        "We recommend to Buy Gold at 1750, Target Price: 1900, Stop Loss: 1700, Generated on: 01-Sep-2024.\n\nPlace your trade through MO Investor App www.tradeapp1.com or MO Trader App www.tradeapp2.com today.\n\nWarm Regards,\nTeam MOFSL",
                        "We recommend to Sell Oil Futures at 70, Target Price: 75, Stop Loss: 65, Generated on: 02-Sep-2024.\n\nPlace your trade through MO Investor App www.tradewithus.com or MO Trader App www.tradeeasy.com today.\n\nWarm Regards,\nTeam MOFSL",

                        "Hello from redBus!\n\nWe are delighted that you chose to travel with us.\n\nYour bus booking from New York to Washington is confirmed with Greyhound for 05-Sep-2024 at 10:00 AM.\n\nHere are the details:\n\nTicket No: 12345\nBus Operator: Greyhound\nSeat No: 12\nDate: 05-Sep-2024\nTime: 10:00 AM\n\nPlease reach the boarding point 15 minutes before departure.\n\nThank you,\nTeam redBus",
                        "Hello from redBus!\n\nWe are delighted that you chose to travel with us.\n\nYour bus booking from Los Angeles to San Francisco is confirmed with Megabus for 10-Sep-2024 at 08:00 PM.\n\nHere are the details:\n\nTicket No: 67890\nBus Operator: Megabus\nSeat No: 5\nDate: 10-Sep-2024\nTime: 08:00 PM\n\nPlease reach the boarding point 15 minutes before departure.\n\nThank you,\nTeam redBus");

        public static List<String> exampleTextsTemplateNames = List.of("alert_1", "alert_1", "commodity_0630",
                        "commodity_0630",
                        "existing_customer_001", "existing_customer_001", "au_drive", "au_drive", "vw45", "vw45",
                        "teacher_slots_new", "teacher_slots_new", "trial_certificate_unlock",
                        "trial_certificate_unlock", "trial_com_24hours_new_apt", "trial_com_24hours_new_apt",
                        "hack4_provi", "hack4_provi", "enquiry_update_rcnt", "enquiry_update_rcnt", "app_1", "app_1",
                        "invest_idea", "invest_idea", "latam_mticket_copax_en", "latam_mticket_copax_en");

}
