name: template-matching
services:
    elasticsearch:
        ports:
            - 127.0.0.1:9200:9200
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.http.ssl.enabled=false
            - xpack.license.self_generated.type=basic
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    kibana:
        ports:
            - 127.0.0.1:5601:5601
        container_name: kibana
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - xpack.security.enabled=false
            - xpack.license.self_generated.type=basic
        image: docker.elastic.co/kibana/kibana:8.15.0